# Generated by Django 6.1 on 2026-08-14 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="프로필 사진",
                        null=True,
                        upload_to="profile_images/",
                    ),
                ),
                (
                    "position_team",
                    models.CharField(
                        blank=True,
                        default="PM · Acme팀",
                        help_text="직함 및 소속 팀",
                        max_length=100,
                    ),
                ),
                (
                    "completed_rehearsals_count",
                    models.PositiveIntegerField(
                        default=0, help_text="완료한 리허설 총 횟수"
                    ),
                ),
                (
                    "notification_enabled",
                    models.BooleanField(default=True, help_text="알림 받기 On/Off"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="한국어", help_text="기본 번역 선호 언어", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
