# Generated by Django 6.1 on 2026-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_actionitem_meetingmemo_meetingsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('ACCEPTED', '수락'), ('REJECTED', '거절')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
