# Generated by Django 6.1 on 2026-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingparticipant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
