# Generated by Django 6.1 on 2026-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meetingsession_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
