# Generated by Django 6.1 on 2026-08-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meetingparticipant_left_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingsession',
            name='started_at',
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
