# Generated by Django 6.1 on 2026-08-14 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMeetingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "room_code",
                    models.CharField(
                        blank=True,
                        help_text="meetings.MeetingSession.room_code",
                        max_length=50,
                    ),
                ),
                ("scheduled_start_time_utc", models.DateTimeField()),
                (
                    "participant_ids",
                    models.JSONField(
                        default=list,
                        help_text="확정 시점 참가자 user id 목록(호스트 포함)",
                    ),
                ),
                (
                    "meetings_sync_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("SYNCED", "동기화 완료"),
                            ("FAILED", "동기화 실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("meetings_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_meeting_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        help_text="0=월요일 ... 6=일요일 (UTC 기준)"
                    ),
                ),
                (
                    "half_hour_index",
                    models.PositiveSmallIntegerField(
                        help_text="0~47, 하루 중 30분 단위 슬롯 인덱스 (UTC 00:00부터)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMFORTABLE", "편한 시간"),
                            ("NEUTRAL", "보통"),
                            ("UNCOMFORTABLE", "불편한 시간"),
                        ],
                        default="NEUTRAL",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["weekday", "half_hour_index"],
                        name="tracker_ava_weekday_cfac32_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "weekday", "half_hour_index"),
                        name="tracker_unique_participant_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParticipationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_meeting_id",
                    models.CharField(
                        blank=True,
                        help_text="meetings.MeetingSession.room_code (있으면)",
                        max_length=100,
                    ),
                ),
                ("meeting_title", models.CharField(blank=True, max_length=255)),
                ("meeting_time_utc", models.DateTimeField(help_text="회의 시각 (UTC)")),
                (
                    "local_timezone",
                    models.CharField(
                        default="UTC",
                        help_text="참가자 로컬 IANA 타임존 (예: Asia/Seoul)",
                        max_length=64,
                    ),
                ),
                (
                    "local_region",
                    models.CharField(
                        blank=True,
                        help_text="참가자 지역 표시명(meetings가 전달). 없으면 타임존으로 대체 표시",
                        max_length=100,
                    ),
                ),
                (
                    "speaking_duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="회의 중 발화 시간(초). meetings가 회의 종료 후 전달",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-meeting_time_utc"],
                "indexes": [
                    models.Index(
                        fields=["participant", "-meeting_time_utc"],
                        name="tracker_par_partici_da0e2c_idx",
                    )
                ],
            },
        ),
    ]
