# Generated by Django 6.1 on 2026-08-12 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "partner_tag",
                    models.CharField(
                        help_text="상대 태그 (예: 독일 팀장님)", max_length=50
                    ),
                ),
                (
                    "situation_label",
                    models.CharField(help_text="상황 라벨", max_length=100),
                ),
                ("text_ko", models.TextField(help_text="원문 (한국어)")),
                ("text_translated", models.TextField(help_text="번역문 (원어)")),
                (
                    "language_code",
                    models.CharField(
                        help_text="번역문 언어 코드 (예: de, ja, zh, en)", max_length=10
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="개선 방향 코멘트 (rehearsal에서 전달, optional)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
